onlyBuiltDependencies:
  - '@clerk/shared'
  - '@fission-ai/openspec'
  - '@prisma/engines'
  - esbuild
  - prisma

packageExtensions:
  '@hookform/resolvers@*':
    peerDependencies:
      zod: ^4.0.0
